sudo: required
language: node_js
node_js:
  - "8"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cd pkg
  - export PATH=$PATH:$(npm bin)
  - npm install
  - gulp
script: gulp test:ci
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
